name:                uaa-hs
version:             0.1.0.0
github:              "nieled/uaa-hs"
license:             BSD3
author:              "Daniel Calle"
maintainer:          "nieled@riseup.net"
copyright:           "2022 Daniel Calle"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nieled/uaa-hs#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- data-has
- katip
- mono-traversable
- mtl
- regex-tdfa
- raw-strings-qq
- resource-pool
- postgresql-simple
- postgresql-migration
- safe-exceptions
- stm
- string-random
- template-haskell
- text
- time
- time-lens

default-extensions:
- ConstraintKinds
- FlexibleContexts
- GeneralizedNewtypeDeriving
- OverloadedStrings
- QuasiQuotes
- TemplateHaskell

library:
  source-dirs: src

executables:
  uaa-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uaa-hs

tests:
  uaa-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uaa-hs
