name: Haskell CI

on:
  push:
    branches: [ "*" ]
    paths-ignore: 
    - '*.md'
  pull_request:
    branches: [ "*" ]
    paths-ignore: 
    - '*.md'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        versions:
          - ghc: '9.2.3'
            cabal: '3.6.2.0'
            prefix: ''
            cabalopts: '-f-embed_data_files'
            testopts: '--test-option=--hide-successes --test-option=--ansi-tricks=false'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.versions.ghc }}
        cabal-version: ${{ matrix.versions.cabal }}

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all

